// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWatchlist.Api.Models;

#nullable disable

namespace MovieWatchlist.Api.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250710212848_UpdateFavouriteMovieKey")]
    partial class UpdateFavouriteMovieKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FavouriteMovie", b =>
                {
                    b.Property<string>("ImdbID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ImdbID");

                    b.ToTable("FavouriteMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
